{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.2b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.2b.jar",
          "url": "ksp-0.1.2b.jar",
          "size": 8372,
          "sha512": "b294726625b173930b9803eca639384ce397c46471bf339b7bc7a63df75797d0617e73c3cba7f10f2979502e323ca87f9258931465715231b5a0975d250fb6c0",
          "sha256": "559e4ee8083a1dd3d60c4db8a075ba823f2378f0306a91da7839fe3d609dd225",
          "sha1": "aaf3f97c10686e9136404394e494f03797760c80",
          "md5": "44bdd14969ffe3f84daf97c82ef7c2d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.2b"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.2b.jar",
          "url": "ksp-0.1.2b.jar",
          "size": 8372,
          "sha512": "b294726625b173930b9803eca639384ce397c46471bf339b7bc7a63df75797d0617e73c3cba7f10f2979502e323ca87f9258931465715231b5a0975d250fb6c0",
          "sha256": "559e4ee8083a1dd3d60c4db8a075ba823f2378f0306a91da7839fe3d609dd225",
          "sha1": "aaf3f97c10686e9136404394e494f03797760c80",
          "md5": "44bdd14969ffe3f84daf97c82ef7c2d9"
        }
      ]
    }
  ]
}
