{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.2f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.2f.jar",
          "url": "ksp-0.1.2f.jar",
          "size": 8372,
          "sha512": "f8024e2aa190b3fc1c3b6201c0f93734a8f098985b651e02342897d599ffe2415c8f1ca571d1e7d3ec6e46b040db6c53a4c6423fb9e1bca8c85e14c497387a3a",
          "sha256": "9ca7fa5a36298d99587a416e88a757f007868d048a3f44f5382b53c41ac6cfa3",
          "sha1": "9ae6bf6ffdfda564df668f5a6e360ba4c6b140bc",
          "md5": "ef0477dd712a9ec224a7c5c7f7cf525d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.2f"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.2f.jar",
          "url": "ksp-0.1.2f.jar",
          "size": 8372,
          "sha512": "f8024e2aa190b3fc1c3b6201c0f93734a8f098985b651e02342897d599ffe2415c8f1ca571d1e7d3ec6e46b040db6c53a4c6423fb9e1bca8c85e14c497387a3a",
          "sha256": "9ca7fa5a36298d99587a416e88a757f007868d048a3f44f5382b53c41ac6cfa3",
          "sha1": "9ae6bf6ffdfda564df668f5a6e360ba4c6b140bc",
          "md5": "ef0477dd712a9ec224a7c5c7f7cf525d"
        }
      ]
    }
  ]
}
