{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "0.1.5d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.5d.jar",
          "url": "Kore-0.1.5d.jar",
          "size": 584594,
          "sha512": "0bd294283e49d6d6b58a9930ab76cfe7cb6e24c7a279a35ea02f1f98240befd1a28cb6092901cdb06fb63626be8211f95cf9d885a86124b59e8a88b1a84e8235",
          "sha256": "8c89d2f3086c921fafefcb6040c7641ff20ec94539dad79ab7e91186aaf9f532",
          "sha1": "15fdb119aeb7a799ded2d3c9a49f936aa4cfba1d",
          "md5": "70e7910c5d19fd7079a4215b016adb4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.5d-all.jar",
          "url": "Kore-0.1.5d-all.jar",
          "size": 584594,
          "sha512": "b8ea0a59eaca8e826c1ebf4f64fd22e580e2dd252cca331c148a0e9903fe792ca9bd2c7a7640e468294099c27b40bb8996d773b2d6009f400820ec090cb8c41a",
          "sha256": "4b22048e8ff42cb69ebf68bfc02fc08c095f77e2be87509a59f3c9aea11c963e",
          "sha1": "e95b8fba3f3514b326742eed5eaf90066e070d97",
          "md5": "88614a3e3c21338b5309286cc387cc92"
        }
      ]
    }
  ]
}
