{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "0.1.1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.1b.jar",
          "url": "Kore-0.1.1b.jar",
          "size": 531522,
          "sha512": "00f46c278eef2164db060752e6207f85951938555c3d53b706fb6be38573f7332726e82b9e54021126ca6109a93e8c74f22aae1ef105c25cc69a1e49c0d610dc",
          "sha256": "0bd59b9fa14d448ceb802a5d2836efbd5100068bb009dc036f55af37f11115bf",
          "sha1": "a5b8106527716467d81cddcd25e65e5b71d16e7f",
          "md5": "ce2b1499d540bafa2783ca314b8ca0eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.1b-all.jar",
          "url": "Kore-0.1.1b-all.jar",
          "size": 531522,
          "sha512": "60426b4531b23ae2582a784e723bb70b4b09dbb81650634bef0c72f85af8cfaaeb67698d7698ae1c5183abd962d125a66b6e357333d666a07fc40388e0742d22",
          "sha256": "f7eae018555ed3269af7cd4f06e9b47056f366d4f7dcb6a9b573e10254341e1a",
          "sha1": "26330efe050b5a1f6f4de6c830b8488a6c9191e3",
          "md5": "dbab3c3fef8c29e6631943b82af8dc72"
        }
      ]
    }
  ]
}
