{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "1.21.10-0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-1.21.10-0.1.0.jar",
          "url": "ksp-1.21.10-0.1.0.jar",
          "size": 8433,
          "sha512": "c155e25270da6e6c645719bce06492d68826cdd5720fced6f0616785987336a4353e68f267b0f554b117539f8a41e2cff8f11ba99a1566ee0c9e26e25d2c6a70",
          "sha256": "99356dda8ef73bcaffb6ad4db3e9a6edbac340bfcf941ecaa61cbb591397bebd",
          "sha1": "c9314a66cd038e7f5847ed0a8f879e6aa3cd5d72",
          "md5": "edaced8960505e206818b92d5c2278c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "1.21.10-0.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-1.21.10-0.1.0.jar",
          "url": "ksp-1.21.10-0.1.0.jar",
          "size": 8433,
          "sha512": "c155e25270da6e6c645719bce06492d68826cdd5720fced6f0616785987336a4353e68f267b0f554b117539f8a41e2cff8f11ba99a1566ee0c9e26e25d2c6a70",
          "sha256": "99356dda8ef73bcaffb6ad4db3e9a6edbac340bfcf941ecaa61cbb591397bebd",
          "sha1": "c9314a66cd038e7f5847ed0a8f879e6aa3cd5d72",
          "md5": "edaced8960505e206818b92d5c2278c0"
        }
      ]
    }
  ]
}
