{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "1.21.10-0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-1.21.10-0.1.0.jar",
          "url": "Kore-1.21.10-0.1.0.jar",
          "size": 579612,
          "sha512": "a9b0bdf6d706277adb76556f6fcbd3678034c8fc50e26df12a44f546762683f012721cf293f8b00cae2ed34554b5eea844dfe00f4a9221f85b2d89cdb4809b80",
          "sha256": "59bf5205ba89fcba9c9cf9d1e002fe98cb7a0a7803a5b726371e45524c8c9d8f",
          "sha1": "13c0f8cec639e555b7eb2d12434609505d2730d4",
          "md5": "0cc725e579853eac85cbfb19247fede7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-1.21.10-0.1.0-all.jar",
          "url": "Kore-1.21.10-0.1.0-all.jar",
          "size": 579612,
          "sha512": "5ca7e8aa9f797d7245be7cb58fee8b6f678479e9b1d280c3fa08e1ea210447a71da75b2921991b55850a0b9ccfa3c195316f40372a351f50e80a06971f0913d1",
          "sha256": "3fa9bff631cc76951c5c738275c8905d6b99636105218d7e301ac43125f46c27",
          "sha1": "9ce583f33a1968da5ec0e002c0d43efdf80de9ae",
          "md5": "6fbc9cdee0186364dea3bd833999435b"
        }
      ]
    }
  ]
}
