{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "1.21.10-0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-1.21.10-0.1.1.jar",
          "url": "Kore-1.21.10-0.1.1.jar",
          "size": 595380,
          "sha512": "8277f6138d5b75a6d1f110808decb64b0ba04d19de25cf227076e5770aa620567ed41e4df45811e704b61b12e8c2fee79b2effe85ba5e274d2bc37b4575ec118",
          "sha256": "f5a366e3e679c7aaa386b5207cfba2c77b5484b6953323a8666526f38d01d652",
          "sha1": "c3dc9329f561232ba3cd46e19c4e71005216241e",
          "md5": "30edb368040eedb9bad3c3899f24da3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-1.21.10-0.1.1-all.jar",
          "url": "Kore-1.21.10-0.1.1-all.jar",
          "size": 595380,
          "sha512": "676f7cce74eacbb6f65293c301c880d3913b627d96c15362f9da25f8672eeee521201349e27856d07c29b9d728372bd4ff23cc2f85eed2d846c030f2f3f17718",
          "sha256": "a0170a0c831656d9d6d4f98e0c0e8ae102c491527e321b44ab8c224574c53c66",
          "sha1": "5953885e433f8ec0d11fdf15496be8d4f55c76a3",
          "md5": "638741b84487b51972231e85374e3359"
        }
      ]
    }
  ]
}
