{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "1.21.10-0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-1.21.10-0.1.1.jar",
          "url": "Kore-1.21.10-0.1.1.jar",
          "size": 598487,
          "sha512": "318cd48dcff150855d6fd38147128472ceaa3d87d0e87f56ef3e8790d6642e471674d0696b420e5472a4f4b6c0277e2f379a3d0cccc0c6b975b838a5e3782dab",
          "sha256": "0e68a2eb992556805e5173210d3122e2a75a996627ef01f1fd8b8f4728023de6",
          "sha1": "be7e51839af108381cadeb612754decb4483c439",
          "md5": "487f99e59f89ef737fb662c2ade2e365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-1.21.10-0.1.1-all.jar",
          "url": "Kore-1.21.10-0.1.1-all.jar",
          "size": 598487,
          "sha512": "aa6ce440f208eea830655ebbb17e9535f23e6b934724663a136ef803462faf419ac3bd86c457db5eadf0e814a80f0473d043436282c6f7e40840e1c81a878db1",
          "sha256": "2c0912271dc6463596c5dc0ecaeae945ae4fd01a95b279a8edff9b57e1894ffe",
          "sha1": "507d5df10940b5c9b94e7b7004eb0f0de192cac3",
          "md5": "7cdc869b3935c91c196c9ff7bf45e040"
        }
      ]
    }
  ]
}
