{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.3.jar",
          "url": "Kore-0.1.3.jar",
          "size": 576829,
          "sha512": "757ff22244f63742524f74a5eafc42a0350e518ea74d4ce3da6652d4cbd8e182a93aeb6180518bcb37c963303ba07f27605774c599aab32785c2553d022a7ae8",
          "sha256": "c5221691a108bf01d54b50b6a01038c418c53ea6b65fb454282eb3aa77fd2379",
          "sha1": "4cd54031adc339342cf4d31840706e98a9c9227e",
          "md5": "600b2ad0d6ecca88ebd664b9ed376b7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.3-all.jar",
          "url": "Kore-0.1.3-all.jar",
          "size": 576829,
          "sha512": "0c0f9c848327f13f71d955aac42b38d5e4a1a40ffdd85297ec5cd6378e31382cbb462120be155af4565e7b40e582d669b9437c8a87cd908c46cb8bb06b9d951a",
          "sha256": "1f507286f02e4e9573e560093db9ec656c88773191247a700ab945931cc7915b",
          "sha1": "b85d3aa9713bc4d2caec55e02038664bed93a3cd",
          "md5": "2ad4e68dbf2e47f94fe2ead1198601c8"
        }
      ]
    }
  ]
}
