{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.4c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.4c.jar",
          "url": "ksp-0.1.4c.jar",
          "size": 8372,
          "sha512": "f93ad8f7ee4f98afc2b90e0a2382aa3cffbe9eb0a665df6b2713880ac0c14ace37dc8bf838deb1b4b5a3ef38dc61b9008c583e429dddaabb49d2cd2cb2283186",
          "sha256": "898b29ae8768d8071d1ef94b0c3d27d373869646ba118d9b7831df0e702ad9f9",
          "sha1": "a2d688a03d5d083892cc3a299769568d753b99dd",
          "md5": "1b0c98eb5fbad81d15e89e4171b3d47e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.4c"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.4c.jar",
          "url": "ksp-0.1.4c.jar",
          "size": 8372,
          "sha512": "f93ad8f7ee4f98afc2b90e0a2382aa3cffbe9eb0a665df6b2713880ac0c14ace37dc8bf838deb1b4b5a3ef38dc61b9008c583e429dddaabb49d2cd2cb2283186",
          "sha256": "898b29ae8768d8071d1ef94b0c3d27d373869646ba118d9b7831df0e702ad9f9",
          "sha1": "a2d688a03d5d083892cc3a299769568d753b99dd",
          "md5": "1b0c98eb5fbad81d15e89e4171b3d47e"
        }
      ]
    }
  ]
}
