{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "1.21.10-0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-1.21.10-0.1.1.jar",
          "url": "ksp-1.21.10-0.1.1.jar",
          "size": 8661,
          "sha512": "802c266d017b17e6e220997e801933c439da08dfc6964f96ef725777f608d8f98a225e60efd7f50912b1f422c19daa375dc0cbae4fc8cbff737d94594b1e8a97",
          "sha256": "15069c16405c8b7bfeb269ea79b5e92210e927a9ebeb1454b8f965a01390e207",
          "sha1": "21087d131d0f1924f99ad9a54e05ec694855cc41",
          "md5": "633423b269dbd7a8d5c187369b590ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "1.21.10-0.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-daemon-embeddable"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-compiler-embeddable"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-compiler-impl-embeddable"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm-host"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-daemon-embeddable",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-compiler-embeddable",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-compiler-impl-embeddable",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-scripting-jvm-host",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-1.21.10-0.1.1.jar",
          "url": "ksp-1.21.10-0.1.1.jar",
          "size": 8661,
          "sha512": "802c266d017b17e6e220997e801933c439da08dfc6964f96ef725777f608d8f98a225e60efd7f50912b1f422c19daa375dc0cbae4fc8cbff737d94594b1e8a97",
          "sha256": "15069c16405c8b7bfeb269ea79b5e92210e927a9ebeb1454b8f965a01390e207",
          "sha1": "21087d131d0f1924f99ad9a54e05ec694855cc41",
          "md5": "633423b269dbd7a8d5c187369b590ebf"
        }
      ]
    }
  ]
}
