{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.4.jar",
          "url": "ksp-0.1.4.jar",
          "size": 8372,
          "sha512": "4b259e8796e3b8bcdb43d8aa61bf3b9e0c64d84b82953d9e982123c5bcb08b8a02485c115fa30dbaa29e740306fa1b9996037bddc7b6a9728d8caae9f74bb311",
          "sha256": "cf690e5a5cb6eb7514f17da3f6970977f7ab096cab9d22f3077306589ebfdac5",
          "sha1": "54b08f2cf1270bdf85e74895690b425d5f6b4462",
          "md5": "a3027c8c3bb99c074f34f356edf683ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.4.jar",
          "url": "ksp-0.1.4.jar",
          "size": 8372,
          "sha512": "4b259e8796e3b8bcdb43d8aa61bf3b9e0c64d84b82953d9e982123c5bcb08b8a02485c115fa30dbaa29e740306fa1b9996037bddc7b6a9728d8caae9f74bb311",
          "sha256": "cf690e5a5cb6eb7514f17da3f6970977f7ab096cab9d22f3077306589ebfdac5",
          "sha1": "54b08f2cf1270bdf85e74895690b425d5f6b4462",
          "md5": "a3027c8c3bb99c074f34f356edf683ef"
        }
      ]
    }
  ]
}
