{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kito.kore_ksp",
    "module": "ksp",
    "version": "0.1.0b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.0b.jar",
          "url": "ksp-0.1.0b.jar",
          "size": 8372,
          "sha512": "4e511dcbe90c8896ee030df8317760eb2e38c131701843fcc35a646b75edb9f4f90fd157c06b362efee077f473cbe0537a30c1b8a124e9006b0a70966d518f04",
          "sha256": "6c055d4a4f03af6feea3b387c89f88b21018ddf24ef4e04bf3496cf59428f036",
          "sha1": "b283004b96e04ec31329942936f1471381e43cdf",
          "md5": "2490d86a940c9778a71b4d2990b933de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "io.github.augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.0b"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.0b.jar",
          "url": "ksp-0.1.0b.jar",
          "size": 8372,
          "sha512": "4e511dcbe90c8896ee030df8317760eb2e38c131701843fcc35a646b75edb9f4f90fd157c06b362efee077f473cbe0537a30c1b8a124e9006b0a70966d518f04",
          "sha256": "6c055d4a4f03af6feea3b387c89f88b21018ddf24ef4e04bf3496cf59428f036",
          "sha1": "b283004b96e04ec31329942936f1471381e43cdf",
          "md5": "2490d86a940c9778a71b4d2990b933de"
        }
      ]
    }
  ]
}
