{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "0.1.3d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.3d.jar",
          "url": "Kore-0.1.3d.jar",
          "size": 577863,
          "sha512": "f59463beeb6304dd9bbf5f54e02eab4c558d534f2729099d7bb80325c96ce9360b954b22085e8173f7c50845a3a7da14f77ca7a13e4b04939de65a773140bed9",
          "sha256": "444e79f749c2308b4d8b0fa2081b81634826c9198fab515b06e42452fa1d55af",
          "sha1": "25c1795088b3c7c1e90734fe2571f9f3ee93b017",
          "md5": "557d6288cbcd26d3e0fa5f6dc30d06f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.3d-all.jar",
          "url": "Kore-0.1.3d-all.jar",
          "size": 577863,
          "sha512": "2c62c1f54ceb5b62c5ba260045b076deac863bce6223c403e44aa537e7eac457b53a7734f8fca669f3ae91982508e7c54d35e2abc3ebbe1198beed1e3802455d",
          "sha256": "e15065891ae855ed6abed55be2d31a8be8b7763cbb7a7b46e2c0e6f846cced06",
          "sha1": "ce2ebf9d3d974d9974237b68668a85ed61833c90",
          "md5": "dbbab9ed99693251ae873765b9e862b6"
        }
      ]
    }
  ]
}
