{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener",
    "module": "Kore",
    "version": "0.1.4c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.4c.jar",
          "url": "Kore-0.1.4c.jar",
          "size": 575555,
          "sha512": "3813d6ad2bf8042276b13a41e54064b9b3412e4e7e57a393654f79324760cdfd8b4354c186fa8f872ca1de33b7c504aaf88c3877ac37714cde145c4990ce4fd0",
          "sha256": "3e60c7acc623cf599b753b2ad556adaa21d1371bf088cf4b437ca9c4232a6fe5",
          "sha1": "f4ba203dce5c84cded69083f5be3ec235f555947",
          "md5": "3e497c7e95045dae4d4ba788ec043bf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.4c-all.jar",
          "url": "Kore-0.1.4c-all.jar",
          "size": 575555,
          "sha512": "d5b098d5adf6c5d3b92de049684da9ba4f0aff9f0806ee8286d9d955f771a057f0a3c7b64790fa92b0bd7ec65ac3972b9f6a2d9484f67814068bb3084d6581f9",
          "sha256": "c48f79ab19a381038292cb9e5010ee0497be2a2bba35ef1d305729d56044e2b4",
          "sha1": "35698bce9c7c8a143b9f934091cfe0ef7871532e",
          "md5": "911181a8cf3597d29404b0617fa0aa15"
        }
      ]
    }
  ]
}
