{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.3.jar",
          "url": "ksp-0.1.3.jar",
          "size": 8372,
          "sha512": "53c27792faeec993f9cf1a21a74dc1bf1830c9bce948bdcfb09c00706706c89ff14fc45cc4173dbc1a5813e75752233861d24b5fe3145c97ba7f958decd8a680",
          "sha256": "6f5f1b8959c8431cebb3f950ef176a4b4840b0b8ff9cc3973aa43fee0f148abf",
          "sha1": "9f42b5e6da4dec548155e48f8cb96e88189c463a",
          "md5": "5e021b50236be60d8f8f12e9b659db2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.3.jar",
          "url": "ksp-0.1.3.jar",
          "size": 8372,
          "sha512": "53c27792faeec993f9cf1a21a74dc1bf1830c9bce948bdcfb09c00706706c89ff14fc45cc4173dbc1a5813e75752233861d24b5fe3145c97ba7f958decd8a680",
          "sha256": "6f5f1b8959c8431cebb3f950ef176a4b4840b0b8ff9cc3973aa43fee0f148abf",
          "sha1": "9f42b5e6da4dec548155e48f8cb96e88189c463a",
          "md5": "5e021b50236be60d8f8f12e9b659db2a"
        }
      ]
    }
  ]
}
