{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.0.jar",
          "url": "ksp-0.1.0.jar",
          "size": 8372,
          "sha512": "66286fe0fcc9976ed6418ab7196d4aa2a7b8ed609a8e854168281a941869b9e9f358ac111d8735db1d260941b06ec4c8114cd1319c75571209c3aabc3af91036",
          "sha256": "8826aaa4efcab524a0c4249378478f4fd1923df3eb5a42abcc1cb5aef299d6c5",
          "sha1": "3df8aa4a5e691d8c352a368aa16abbc87b6d8443",
          "md5": "f634a3dc7501ac52299bc5a2e0253ed8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.0.jar",
          "url": "ksp-0.1.0.jar",
          "size": 8372,
          "sha512": "66286fe0fcc9976ed6418ab7196d4aa2a7b8ed609a8e854168281a941869b9e9f358ac111d8735db1d260941b06ec4c8114cd1319c75571209c3aabc3af91036",
          "sha256": "8826aaa4efcab524a0c4249378478f4fd1923df3eb5a42abcc1cb5aef299d6c5",
          "sha1": "3df8aa4a5e691d8c352a368aa16abbc87b6d8443",
          "md5": "f634a3dc7501ac52299bc5a2e0253ed8"
        }
      ]
    }
  ]
}
