{
  "formatVersion": "1.1",
  "component": {
    "group": "augustomegener.kore",
    "module": "ksp",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.0.jar",
          "url": "ksp-0.1.0.jar",
          "size": 8372,
          "sha512": "bed5ab91e5670bbf29be1e58eb4a7bdb252beea1fa1183848dbb77a592f0f52759a30c3a5cfe6cf6a2d0196e18469560dfe9b7143f3dab485062f3f5ad14fa62",
          "sha256": "bf81ef72f6792e310b0c8a82a1b3bfa223ecedf85b0c46af0766b4dff4dd4cbd",
          "sha1": "b20ec47c2fc403f3af88a2c8dc2e7f7be73a7eac",
          "md5": "9cdda10214e37cd4e4c0b0f46e0181ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "augustomegener",
          "module": "Kore",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-compiler",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-1.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.0.jar",
          "url": "ksp-0.1.0.jar",
          "size": 8372,
          "sha512": "bed5ab91e5670bbf29be1e58eb4a7bdb252beea1fa1183848dbb77a592f0f52759a30c3a5cfe6cf6a2d0196e18469560dfe9b7143f3dab485062f3f5ad14fa62",
          "sha256": "bf81ef72f6792e310b0c8a82a1b3bfa223ecedf85b0c46af0766b4dff4dd4cbd",
          "sha1": "b20ec47c2fc403f3af88a2c8dc2e7f7be73a7eac",
          "md5": "9cdda10214e37cd4e4c0b0f46e0181ea"
        }
      ]
    }
  ]
}
