{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.augustomegener",
    "module": "Kore",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.0.jar",
          "url": "Kore-0.1.0.jar",
          "size": 510922,
          "sha512": "acf95e728430a8f133db7f6a30c946987a99d247adf8dbef2f878865566ce46d0f7c5cefadd8bd1d917758aee39c70091a1efd690cba5fa593fd2e407e968d54",
          "sha256": "ffbf54dabbeb2ba5b053a8939ef824bc1943d7d43863babe40111e1e046f5f10",
          "sha1": "380654e4fc92cde0e8bc3581d300a7baebbeeb32",
          "md5": "f1a1dc768d339008f12fe25814202313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "Kore-0.1.0.jar",
          "url": "Kore-0.1.0.jar",
          "size": 510922,
          "sha512": "acf95e728430a8f133db7f6a30c946987a99d247adf8dbef2f878865566ce46d0f7c5cefadd8bd1d917758aee39c70091a1efd690cba5fa593fd2e407e968d54",
          "sha256": "ffbf54dabbeb2ba5b053a8939ef824bc1943d7d43863babe40111e1e046f5f10",
          "sha1": "380654e4fc92cde0e8bc3581d300a7baebbeeb32",
          "md5": "f1a1dc768d339008f12fe25814202313"
        }
      ]
    }
  ]
}
